### ISSUE TITLE
Handicap games - rated?

### ISSUE THREAD

**Issue by CouchTomato87** [CouchTomato87/InternationalizedPieces#3]
It looks like for Shogi, I can choose a handicap, but I can still select rated and create a game... I haven't checked to see if that actually goes through to a real handicap game, but once that's selected that shouldn't be an option.

Similarly, I can still put an FEN in any variant and still have the option to choose rated.

Maybe what would make sense is that if you have rated selected, the FEN and handicap dropdown list should be grayed out? And if you choose a handicap or FEN, then casual should automatically be selected

**Comment by gbtami** [comment]
Fixed. Thx!

**Comment by CouchTomato87** [comment]
LOL I don't know why I put this here, whoops!
